#4 added userContext, header/layout/footer components
mz106/accountability-fe pull request #5
Opened 2023-01-21 17:22 UTC by heydut

2023-01-21 19:09 UTC, mz106 requested changes
Dut, my bad. I know that you did what was in the issue but I got it wrong. Please see changes below. Sorry.

2023-01-21 19:09 UTC, mz106 commented on src/components/Layout/Layout.jsx
> +      <Header />
Please wrap wrap layout header, children and footer and add dummy state to layout component

2023-01-21 19:09 UTC, mz106 commented on src/index.js
> +    <UserContextProvider>
Please remove UserContext wrapper and swap with layout after the above changes

2023-01-21 19:11 UTC, mz106 commented
Also Dut, remember to assign yourself to the pull requests - your GH profile will have an increased number of pull requests if you do that.

2023-01-21 22:21 UTC, heydut commented
What you asked looks a little confusing for me and I'm not sure I understood it correctly, but I made some changes.

2023-01-23 13:28 UTC, mz106 commented
Hi Dut. Please look at the following link;

https://github.com/mz106/testing-react-sequelize/blob/main/library-test-fe/src/components/layout/Layout.js

In here, the Layout component returns the header, children and footer. These are wrapped by the UserContext.Proveder. Then Layout component then wraps the App component in index.js;

https://github.com/mz106/testing-react-sequelize/blob/main/library-test-fe/src/index.js

This is so that multiple contexts can be hidden in the Layout component and also allow access to all pages for the header and footer, as well as any context required globally.

2023-01-23 13:28 UTC, mz106 commented on src/index.js
> +    <UserContextProvider>
Please see my below comment

2023-01-23 17:43 UTC, mz106 approved these changes
Approved. Thanks Dut. Good to merge.

2023-01-23 17:43 UTC, mz106 commented on src/components/Layout/Layout.jsx
> +      <Header />
Ok to go.

2023-01-24 01:58 UTC, merged